# Site
title: Bhaskoro Muthohar
description: Data Scientist
url: https://bhaskoro-muthohar.github.io/
logo: foto.png                                       # Site logo
locale: en_US

# Left Block Images
background:
  homepage: images/home.jpg                           # this image will be shown on homepage's left block
  post-list: images/post.jpg             # this image will be shown on post list page
  default-post: images/postdepth.jpg   # this image will be shown when post's front matter doesn't specify any image

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed

# Google Analytics
google-analytics: UA-156457186-1

# Social Links
email:              bhaskoro.jr@gmail.com
#google.plus:        username
#twitter:            Bhaskoro_AM
#facebook:           username
github:             bhaskoro-muthohar
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:           bhaskoro-muthohar
#xing:              username
instagram:          bhaskoro.muthohar
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
steam:              amethyst12
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
#behance:           username

# Gems
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

# Exclude list
include: [_pages]
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile, .sass-cache, .DS_Store]
